"""更改了Problem和Class模型

Revision ID: 07533bbb6d85
Revises: da0422374078
Create Date: 2020-04-19 08:46:26.120111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07533bbb6d85'
down_revision = 'da0422374078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('join_code', sa.String(length=64), nullable=True))
    op.add_column('problems', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_problems_timestamp'), 'problems', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_timestamp'), table_name='problems')
    op.drop_column('problems', 'timestamp')
    op.drop_column('classes', 'join_code')
    # ### end Alembic commands ###
