"""fix ocrresult-problem relation

Revision ID: 0d6c377b5e1f
Revises: d0d946ef7790
Create Date: 2025-01-27 17:17:16.521512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d6c377b5e1f'
down_revision: Union[str, None] = 'd0d946ef7790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
