"""fix ocrresult-problem relation

Revision ID: 10fc24f54d90
Revises: c6593ea6eda1
Create Date: 2025-01-27 17:11:28.144191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10fc24f54d90'
down_revision: Union[str, None] = 'c6593ea6eda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ocrbox_be_chosen_by_id_fkey', 'ocrbox', type_='foreignkey')
    op.create_foreign_key(None, 'ocrbox', 'ocrresult', ['be_chosen_by_id'], ['id'])
    op.add_column('problem', sa.Column('ocr_result_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'problem', 'ocrresult', ['ocr_result_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'ocr_result_id')
    op.drop_constraint(None, 'ocrbox', type_='foreignkey')
    op.create_foreign_key('ocrbox_be_chosen_by_id_fkey', 'ocrbox', 'problem', ['be_chosen_by_id'], ['id'])
    # ### end Alembic commands ###
