"""add created_at column for Problem

Revision ID: 1d14516587d4
Revises: dd49cdfdb4b3
Create Date: 2025-01-30 18:09:07.873817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '1d14516587d4'
down_revision: Union[str, None] = 'dd49cdfdb4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now())))  # updated: set server default for exisiting entities
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'created_at')
    # ### end Alembic commands ###
