"""fix ocrresult-ocrbox relation

Revision ID: 1fc3f0da97ce
Revises: 390cc0d2f290
Create Date: 2025-01-27 17:32:57.534540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fc3f0da97ce'
down_revision: Union[str, None] = '390cc0d2f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('ocrresult_chosen_box_id_fkey', 'ocrresult', type_='foreignkey')
    # op.create_foreign_key(None, 'ocrresult', 'ocrbox', ['chosen_box_id'], ['be_chosen_by_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'ocrresult', type_='foreignkey')
    # op.create_foreign_key('ocrresult_chosen_box_id_fkey', 'ocrresult', 'ocrbox', ['chosen_box_id'], ['id'])
    # ### end Alembic commands ###
