"""add subject id for User

Revision ID: 22b90d565877
Revises: cdfd5888c7f1
Create Date: 2025-01-18 21:00:41.609334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22b90d565877'
down_revision: Union[str, None] = 'cdfd5888c7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'subject_id')
    # ### end Alembic commands ###
