"""fix ocrresult-problem relation

Revision ID: 23a36734c841
Revises: 4f4c4d6f78ea
Create Date: 2025-01-27 17:19:16.755612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23a36734c841'
down_revision: Union[str, None] = '4f4c4d6f78ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
