"""add user role

Revision ID: 312abe9d7d27
Revises: 5ec1fcf44d13
Create Date: 2025-01-18 10:36:58.413755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '312abe9d7d27'
down_revision: Union[str, None] = '5ec1fcf44d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('STUDENT', 'TEACHER', name='userrole').create(op.get_bind())
    op.add_column('user', sa.Column('role', postgresql.ENUM('STUDENT', 'TEACHER', name='userrole', create_type=False), nullable=True))
    op.alter_column('user', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user', 'role')
    sa.Enum('STUDENT', 'TEACHER', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
