"""fix ocrresult-ocrbox relation

Revision ID: 357c298f87d4
Revises: e6e80254523b
Create Date: 2025-01-27 17:36:44.408179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '357c298f87d4'
down_revision: Union[str, None] = 'e6e80254523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
