"""fix ocrresult-ocrbox relation

Revision ID: 390cc0d2f290
Revises: 32cf5817c641
Create Date: 2025-01-27 17:31:10.549558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '390cc0d2f290'
down_revision: Union[str, None] = '32cf5817c641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('ocrbox_be_chosen_by_id_fkey', 'ocrbox', type_='foreignkey')
    # op.create_foreign_key(None, 'ocrbox', 'ocrresult', ['be_chosen_by_id'], ['chosen_box_id'])
    # op.drop_constraint('ocrresult_chosen_box_id_fkey', 'ocrresult', type_='foreignkey')
    # op.create_foreign_key(None, 'ocrresult', 'ocrbox', ['chosen_box_id'], ['be_chosen_by_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'ocrresult', type_='foreignkey')
    # op.create_foreign_key('ocrresult_chosen_box_id_fkey', 'ocrresult', 'ocrbox', ['chosen_box_id'], ['id'])
    # op.drop_constraint(None, 'ocrbox', type_='foreignkey')
    # op.create_foreign_key('ocrbox_be_chosen_by_id_fkey', 'ocrbox', 'ocrresult', ['be_chosen_by_id'], ['id'])
    # ### end Alembic commands ###
