"""multiple classes for a teacher

Revision ID: 4a6f28ead417
Revises: 312abe9d7d27
Create Date: 2025-01-18 20:37:59.823005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a6f28ead417'
down_revision: Union[str, None] = '312abe9d7d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'class', 'user', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    # ### end Alembic commands ###
