"""fix ocrresult-ocrbox relation

Revision ID: 4e3758fdb1c7
Revises: 357c298f87d4
Create Date: 2025-01-27 17:45:42.236806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e3758fdb1c7'
down_revision: Union[str, None] = '357c298f87d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
