"""fix ocrresult-problem relation

Revision ID: 4f4c4d6f78ea
Revises: 0d6c377b5e1f
Create Date: 2025-01-27 17:18:17.337811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f4c4d6f78ea'
down_revision: Union[str, None] = '0d6c377b5e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
