"""修改了User模型以更好地实现班级功能

Revision ID: 4f8ad9c22eba
Revises: 07533bbb6d85
Create Date: 2020-04-19 09:11:59.433925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8ad9c22eba'
down_revision = '07533bbb6d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subject_id')
    # ### end Alembic commands ###
