"""add problem owner

Revision ID: 684261811942
Revises: 847db0cee41f
Create Date: 2025-01-26 21:03:15.816531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '684261811942'
down_revision: Union[str, None] = '847db0cee41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'problem', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'owner_id')
    # ### end Alembic commands ###
