"""trying to fix ocrresult-box foreign key

Revision ID: 7ca72c520d63
Revises: 34843d251b32
Create Date: 2025-01-26 21:33:38.122889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ca72c520d63'
down_revision: Union[str, None] = '34843d251b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocrbox', sa.Column('be_chosen_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'ocrbox', 'problem', ['be_chosen_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocrbox', type_='foreignkey')
    op.drop_column('ocrbox', 'be_chosen_by_id')
    # ### end Alembic commands ###
