"""add user-class relation

Revision ID: 814d310fe9f6
Revises: 11424e4cc1ea
Create Date: 2025-01-17 20:47:30.852319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '814d310fe9f6'
down_revision: Union[str, None] = '11424e4cc1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('class_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'class_id')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
