"""fix ocrresult-ocrbox relation

Revision ID: 817e06c324ea
Revises: eb40fd2c9ca6
Create Date: 2025-01-27 17:53:34.639134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '817e06c324ea'
down_revision: Union[str, None] = 'eb40fd2c9ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ocrbox_be_chosen_by_id_fkey', 'ocrbox', type_='foreignkey')
    op.drop_column('ocrbox', 'be_chosen_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocrbox', sa.Column('be_chosen_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('ocrbox_be_chosen_by_id_fkey', 'ocrbox', 'ocrresult', ['be_chosen_by_id'], ['id'])
    # ### end Alembic commands ###
