"""将错题模型加入了所有者关联

Revision ID: 89e85909d525
Revises: 1dbfc8f9458b
Create Date: 2020-04-18 10:52:19.086882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e85909d525'
down_revision = '1dbfc8f9458b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'author_id')
    # ### end Alembic commands ###
