"""set subject to optional for User

Revision ID: cdfd5888c7f1
Revises: a4b17f4c33ec
Create Date: 2025-01-18 20:58:39.843711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdfd5888c7f1'
down_revision: Union[str, None] = 'a4b17f4c33ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
