"""更换了Tag的存储方式

Revision ID: da0422374078
Revises: b0035e34ec3d
Create Date: 2020-04-18 18:13:03.534779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0422374078'
down_revision = 'b0035e34ec3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'owner_id')
    # ### end Alembic commands ###
