"""fix ocrresult-ocrbox relation

Revision ID: df3b42cf4a90
Revises: 4e3758fdb1c7
Create Date: 2025-01-27 17:47:17.399211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df3b42cf4a90'
down_revision: Union[str, None] = '4e3758fdb1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
