"""fix ocrresult-ocrbox relation

Revision ID: e6e80254523b
Revises: 1fc3f0da97ce
Create Date: 2025-01-27 17:33:41.982664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6e80254523b'
down_revision: Union[str, None] = '1fc3f0da97ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
