"""fix ocrresult-ocrbox relation

Revision ID: eb40fd2c9ca6
Revises: df3b42cf4a90
Create Date: 2025-01-27 17:52:24.117358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb40fd2c9ca6'
down_revision: Union[str, None] = 'df3b42cf4a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problem_ocr_result_id_fkey', 'problem', type_='foreignkey')
    op.drop_column('problem', 'ocr_result_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('ocr_result_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('problem_ocr_result_id_fkey', 'problem', 'ocrresult', ['ocr_result_id'], ['id'])
    # ### end Alembic commands ###
