"""add class invitation code

Revision ID: fd5a5cf32ed1
Revises: b8674f66e87e
Create Date: 2025-01-24 20:51:26.799007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd5a5cf32ed1'
down_revision: Union[str, None] = 'b8674f66e87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('invitation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'invitation_code')
    # ### end Alembic commands ###
